#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaBroadcastHUD

#include "Basic.hpp"

#include "AthenaBroadcastHUD_classes.hpp"
#include "AthenaBroadcastHUD_parameters.hpp"


namespace SDK
{

// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.AllWinnersAnnoucedDelegateEvent
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FAthenaWinnerInfo                WinnerInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaBroadcastHUD_C::AllWinnersAnnoucedDelegateEvent(const struct FAthenaWinnerInfo& WinnerInfo)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AllWinnersAnnoucedDelegateEvent");

	Params::AthenaBroadcastHUD_C_AllWinnersAnnoucedDelegateEvent Parms{};

	Parms.WinnerInfo = std::move(WinnerInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.BindBroadcastEvents
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::BindBroadcastEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BindBroadcastEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.BindGameStateEvents
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameStateAthena                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::BindGameStateEvents(class AFortGameStateAthena* GameStateAthena)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BindGameStateEvents");

	Params::AthenaBroadcastHUD_C_BindGameStateEvents Parms{};

	Parms.GameStateAthena = GameStateAthena;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.BindReplayContextEvents
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::BindReplayContextEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BindReplayContextEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.BindSpectatingEvents
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::BindSpectatingEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BindSpectatingEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.BndEvt__BattleBusButton_K2Node_ComponentBoundEvent_27_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonLegacy*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::BndEvt__BattleBusButton_K2Node_ComponentBoundEvent_27_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__BattleBusButton_K2Node_ComponentBoundEvent_27_CommonButtonClicked__DelegateSignature");

	Params::AthenaBroadcastHUD_C_BndEvt__BattleBusButton_K2Node_ComponentBoundEvent_27_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.CheckIfCreativeOrPlayground
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameStateAthena                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::CheckIfCreativeOrPlayground(class AFortGameStateAthena* GameStateAthena)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CheckIfCreativeOrPlayground");

	Params::AthenaBroadcastHUD_C_CheckIfCreativeOrPlayground Parms{};

	Parms.GameStateAthena = GameStateAthena;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaBroadcastHUD_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaBroadcastHUD_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.ExecuteUbergraph_AthenaBroadcastHUD
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::ExecuteUbergraph_AthenaBroadcastHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_AthenaBroadcastHUD");

	Params::AthenaBroadcastHUD_C_ExecuteUbergraph_AthenaBroadcastHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.GamePhaseChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAthenaGamePhase                        NewPhase                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::GamePhaseChanged(EAthenaGamePhase NewPhase)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GamePhaseChanged");

	Params::AthenaBroadcastHUD_C_GamePhaseChanged Parms{};

	Parms.NewPhase = NewPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleCameraChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerSpectating*  PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESpectatorCameraType                    CameraType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleCameraChange(class AFortPlayerControllerSpectating* PlayerController, ESpectatorCameraType CameraType)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleCameraChange");

	Params::AthenaBroadcastHUD_C_HandleCameraChange Parms{};

	Parms.PlayerController = PlayerController;
	Parms.CameraType = CameraType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleCursorModeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCursorModeEnabled                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      CustomWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleCursorModeChanged(bool bCursorModeEnabled, class FName ActionName, class UUserWidget* CustomWidget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleCursorModeChanged");

	Params::AthenaBroadcastHUD_C_HandleCursorModeChanged Parms{};

	Parms.bCursorModeEnabled = bCursorModeEnabled;
	Parms.ActionName = ActionName;
	Parms.CustomWidget = CustomWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleHighlightPlayingEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsPlaying                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleHighlightPlayingEvent(bool bIsPlaying)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleHighlightPlayingEvent");

	Params::AthenaBroadcastHUD_C_HandleHighlightPlayingEvent Parms{};

	Parms.bIsPlaying = bIsPlaying;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleHudNotificationSuppressionChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldSuppress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleHudNotificationSuppressionChange(bool bShouldSuppress)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleHudNotificationSuppressionChange");

	Params::AthenaBroadcastHUD_C_HandleHudNotificationSuppressionChange Parms{};

	Parms.bShouldSuppress = bShouldSuppress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleSequencerPlaybackReadyEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsPlaybackReady                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleSequencerPlaybackReadyEvent(bool bIsPlaybackReady)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleSequencerPlaybackReadyEvent");

	Params::AthenaBroadcastHUD_C_HandleSequencerPlaybackReadyEvent Parms{};

	Parms.bIsPlaybackReady = bIsPlaybackReady;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HandleSessionIdWatermarkVisibilityChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HandleSessionIdWatermarkVisibilityChanged(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleSessionIdWatermarkVisibilityChanged");

	Params::AthenaBroadcastHUD_C_HandleSessionIdWatermarkVisibilityChanged Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HideGameOver
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::HideGameOver()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HideGameOver");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.HUDVisibilitySound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EHudVisibilityState                     HUDVisibility                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::HUDVisibilitySound(EHudVisibilityState HUDVisibility)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HUDVisibilitySound");

	Params::AthenaBroadcastHUD_C_HUDVisibilitySound Parms{};

	Parms.HUDVisibility = HUDVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.IsPlayerInGameOver
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bIsPlayerInGameOver                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasPlayerEliminated                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::IsPlayerInGameOver(bool* bIsPlayerInGameOver, bool* bWasPlayerEliminated)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("IsPlayerInGameOver");

	Params::AthenaBroadcastHUD_C_IsPlayerInGameOver Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsPlayerInGameOver != nullptr)
		*bIsPlayerInGameOver = Parms.bIsPlayerInGameOver;

	if (bWasPlayerEliminated != nullptr)
		*bWasPlayerEliminated = Parms.bWasPlayerEliminated;
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnAllWinnersAnnounced
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Displayed                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnAllWinnersAnnounced(bool* Displayed)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnAllWinnersAnnounced");

	Params::AthenaBroadcastHUD_C_OnAllWinnersAnnounced Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Displayed != nullptr)
		*Displayed = Parms.Displayed;
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnCountdownFinished
// (BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::OnCountdownFinished()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCountdownFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnCountdownStarted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TimeRemaining                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnCountdownStarted(int32 TimeRemaining)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCountdownStarted");

	Params::AthenaBroadcastHUD_C_OnCountdownStarted Parms{};

	Parms.TimeRemaining = TimeRemaining;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnExtensionWidgetCreated
// (Event, Protected, BlueprintEvent)
// Parameters:
// EUIExtensionSlot                        ExtensionSlot                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnExtensionWidgetCreated(EUIExtensionSlot ExtensionSlot, class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExtensionWidgetCreated");

	Params::AthenaBroadcastHUD_C_OnExtensionWidgetCreated Parms{};

	Parms.ExtensionSlot = ExtensionSlot;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnExtensionWidgetRemoved
// (Event, Protected, BlueprintEvent)
// Parameters:
// EUIExtensionSlot                        ExtensionSlot                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnExtensionWidgetRemoved(EUIExtensionSlot ExtensionSlot, class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExtensionWidgetRemoved");

	Params::AthenaBroadcastHUD_C_OnExtensionWidgetRemoved Parms{};

	Parms.ExtensionSlot = ExtensionSlot;
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnGameStateSet_BP
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameStateAthena                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnGameStateSet_BP(class AFortGameStateAthena* GameStateAthena)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnGameStateSet_BP");

	Params::AthenaBroadcastHUD_C_OnGameStateSet_BP Parms{};

	Parms.GameStateAthena = GameStateAthena;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnHUDScaleChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   HUDScale                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnHUDScaleChanged(float HUDScale)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnHUDScaleChanged");

	Params::AthenaBroadcastHUD_C_OnHUDScaleChanged Parms{};

	Parms.HUDScale = HUDScale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnHudVisibilityChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EHudVisibilityState                     NewVisibility                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnHudVisibilityChanged(EHudVisibilityState NewVisibility)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnHudVisibilityChanged");

	Params::AthenaBroadcastHUD_C_OnHudVisibilityChanged Parms{};

	Parms.NewVisibility = NewVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnIndicatorModeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIndicatorsEnabled                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnIndicatorModeChanged(bool bIndicatorsEnabled)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnIndicatorModeChanged");

	Params::AthenaBroadcastHUD_C_OnIndicatorModeChanged Parms{};

	Parms.bIndicatorsEnabled = bIndicatorsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnLevelStreamingChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bStreaming                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnLevelStreamingChanged(bool bStreaming)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLevelStreamingChanged");

	Params::AthenaBroadcastHUD_C_OnLevelStreamingChanged Parms{};

	Parms.bStreaming = bStreaming;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnMinigameChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortMinigame*                    NewMinigame                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnMinigameChanged(class AFortMinigame* NewMinigame)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMinigameChanged");

	Params::AthenaBroadcastHUD_C_OnMinigameChanged Parms{};

	Parms.NewMinigame = NewMinigame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnMinigameStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortMinigame*                    ChangedMinigame                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortMinigameState                      MinigameState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnMinigameStateChanged(class AFortMinigame* ChangedMinigame, EFortMinigameState MinigameState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMinigameStateChanged");

	Params::AthenaBroadcastHUD_C_OnMinigameStateChanged Parms{};

	Parms.ChangedMinigame = ChangedMinigame;
	Parms.MinigameState = MinigameState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnPhaseStepChanged
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TScriptInterface<class IFortSafeZoneInterface>SafeZoneInterface                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EAthenaGamePhaseStep                    NewPhaseStep                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnPhaseStepChanged(const TScriptInterface<class IFortSafeZoneInterface>& SafeZoneInterface, EAthenaGamePhaseStep NewPhaseStep)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPhaseStepChanged");

	Params::AthenaBroadcastHUD_C_OnPhaseStepChanged Parms{};

	Parms.SafeZoneInterface = SafeZoneInterface;
	Parms.NewPhaseStep = NewPhaseStep;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnPipModeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnPipModeChanged(bool bEnabled)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPipModeChanged");

	Params::AthenaBroadcastHUD_C_OnPipModeChanged Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnPlayerDied
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerState*                 InDeadPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnPlayerDied(class AFortPlayerState* InDeadPlayerState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerDied");

	Params::AthenaBroadcastHUD_C_OnPlayerDied Parms{};

	Parms.InDeadPlayerState = InDeadPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnPlayerTargetingChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsTargeting                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnPlayerTargetingChanged(bool bIsTargeting)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerTargetingChanged");

	Params::AthenaBroadcastHUD_C_OnPlayerTargetingChanged Parms{};

	Parms.bIsTargeting = bIsTargeting;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnPlaylistDataChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UFortPlaylistAthena*              PlaylistData                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnPlaylistDataChanged(const class UFortPlaylistAthena* PlaylistData)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlaylistDataChanged");

	Params::AthenaBroadcastHUD_C_OnPlaylistDataChanged Parms{};

	Parms.PlaylistData = PlaylistData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnStartStormSurgeDisplay
// (BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::OnStartStormSurgeDisplay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStartStormSurgeDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnStopStormSurgeDisplay
// (BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::OnStopStormSurgeDisplay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStopStormSurgeDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnToggleFollowedPlayerInfoActionExecuted
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bPassThrough                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnToggleFollowedPlayerInfoActionExecuted(bool* bPassThrough)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnToggleFollowedPlayerInfoActionExecuted");

	Params::AthenaBroadcastHUD_C_OnToggleFollowedPlayerInfoActionExecuted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bPassThrough != nullptr)
		*bPassThrough = Parms.bPassThrough;
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnToggleRemainingPlayersActionExecuted
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bPassThrough                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnToggleRemainingPlayersActionExecuted(bool* bPassThrough)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnToggleRemainingPlayersActionExecuted");

	Params::AthenaBroadcastHUD_C_OnToggleRemainingPlayersActionExecuted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bPassThrough != nullptr)
		*bPassThrough = Parms.bPassThrough;
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnToggleSquadStatusActionExecuted
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bPassThrough                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnToggleSquadStatusActionExecuted(bool* bPassThrough)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnToggleSquadStatusActionExecuted");

	Params::AthenaBroadcastHUD_C_OnToggleSquadStatusActionExecuted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bPassThrough != nullptr)
		*bPassThrough = Parms.bPassThrough;
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnUnableToPerformAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayTagContainer            FailedReason                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             FailureText                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaBroadcastHUD_C::OnUnableToPerformAction(const struct FGameplayTagContainer& FailedReason, const class FText& FailureText)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnUnableToPerformAction");

	Params::AthenaBroadcastHUD_C_OnUnableToPerformAction Parms{};

	Parms.FailedReason = std::move(FailedReason);
	Parms.FailureText = std::move(FailureText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnVolumePromptOpenOrClosed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewlyOpen                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::OnVolumePromptOpenOrClosed(bool NewlyOpen)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnVolumePromptOpenOrClosed");

	Params::AthenaBroadcastHUD_C_OnVolumePromptOpenOrClosed Parms{};

	Parms.NewlyOpen = NewlyOpen;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.OnWinnerAnnounced
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::OnWinnerAnnounced()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnWinnerAnnounced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.SetBattleBusButtonVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::SetBattleBusButtonVisibility(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetBattleBusButtonVisibility");

	Params::AthenaBroadcastHUD_C_SetBattleBusButtonVisibility Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.SetFullscreenMapVisibility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::SetFullscreenMapVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetFullscreenMapVisibility");

	Params::AthenaBroadcastHUD_C_SetFullscreenMapVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.SetupBattlebusButton
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::SetupBattlebusButton()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetupBattlebusButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.ShowGameOver
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShowEliminated                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaBroadcastHUD_C::ShowGameOver(bool bShowEliminated)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ShowGameOver");

	Params::AthenaBroadcastHUD_C_ShowGameOver Parms{};

	Parms.bShowEliminated = bShowEliminated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.ToggleNetUIWidgetVisibility
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::ToggleNetUIWidgetVisibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ToggleNetUIWidgetVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.ToggleOffAirWidgetVisibility
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::ToggleOffAirWidgetVisibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ToggleOffAirWidgetVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.UnbindBroadcastEvents
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::UnbindBroadcastEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UnbindBroadcastEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.UnbindGameStateEvents
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::UnbindGameStateEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UnbindGameStateEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.UnbindSpectatingEvents
// (Private, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::UnbindSpectatingEvents()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UnbindSpectatingEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaBroadcastHUD.AthenaBroadcastHUD_C.UpdateLoadingVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaBroadcastHUD_C::UpdateLoadingVisibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateLoadingVisibility");

	UObject::ProcessEvent(Func, nullptr);
}

}

