#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaEventMatchPlayerGridPlayerWidget

#include "Basic.hpp"

#include "AthenaEventMatchPlayerGridPlayerWidget_classes.hpp"
#include "AthenaEventMatchPlayerGridPlayerWidget_parameters.hpp"


namespace SDK
{

// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.ExecuteUbergraph_AthenaEventMatchPlayerGridPlayerWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::ExecuteUbergraph_AthenaEventMatchPlayerGridPlayerWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_AthenaEventMatchPlayerGridPlayerWidget");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_ExecuteUbergraph_AthenaEventMatchPlayerGridPlayerWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.IsAliveAndNotInAircraft
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bAliveAndNotInAircraft                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::IsAliveAndNotInAircraft(bool* bAliveAndNotInAircraft)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("IsAliveAndNotInAircraft");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_IsAliveAndNotInAircraft Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bAliveAndNotInAircraft != nullptr)
		*bAliveAndNotInAircraft = Parms.bAliveAndNotInAircraft;
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.IsGamePreAircraft
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bIsGamePreAircraft                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::IsGamePreAircraft(bool* bIsGamePreAircraft)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("IsGamePreAircraft");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_IsGamePreAircraft Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsGamePreAircraft != nullptr)
		*bIsGamePreAircraft = Parms.bIsGamePreAircraft;
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnBeingRevivedStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsBeingRevived                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnBeingRevivedStateChanged(class UAthenaRemotePlayerViewData* InPlayerData, bool bIsBeingRevived)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnBeingRevivedStateChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnBeingRevivedStateChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.bIsBeingRevived = bIsBeingRevived;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnDBNOStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsDBNO                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnDBNOStateChanged(class UAthenaRemotePlayerViewData* InPlayerData, bool bIsDBNO)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnDBNOStateChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnDBNOStateChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.bIsDBNO = bIsDBNO;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnDeadStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsDead                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnDeadStateChanged(class UAthenaRemotePlayerViewData* InPlayerData, bool bIsDead)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnDeadStateChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnDeadStateChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.bIsDead = bIsDead;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnDisconnectedChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsDisconnected                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnDisconnectedChanged(class UAthenaRemotePlayerViewData* InPlayerData, bool bIsDisconnected)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnDisconnectedChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnDisconnectedChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.bIsDisconnected = bIsDisconnected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnGridSizeChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InGridSize                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnGridSizeChanged(int32 InGridSize)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnGridSizeChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnGridSizeChanged Parms{};

	Parms.InGridSize = InGridSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnHealthDamaged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InHealth                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InHealthMax                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnHealthDamaged(class UAthenaRemotePlayerViewData* InPlayerData, float InHealth, float InHealthMax)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnHealthDamaged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnHealthDamaged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InHealth = InHealth;
	Parms.InHealthMax = InHealthMax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnHealthHealed
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InHealth                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InHealthMax                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnHealthHealed(class UAthenaRemotePlayerViewData* InPlayerData, float InHealth, float InHealthMax)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnHealthHealed");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnHealthHealed Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InHealth = InHealth;
	Parms.InHealthMax = InHealthMax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnPlayerDataChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnPlayerDataChanged(class UAthenaRemotePlayerViewData* InPlayerData)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerDataChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnPlayerDataChanged Parms{};

	Parms.InPlayerData = InPlayerData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnPlayerNameChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           InPlayerName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnPlayerNameChanged(class UAthenaRemotePlayerViewData* InPlayerData, const class FString& InPlayerName)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerNameChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnPlayerNameChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InPlayerName = std::move(InPlayerName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnPlayerStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortPlayerStateAthena*           InPlayerState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnPlayerStateChanged(class UAthenaRemotePlayerViewData* InPlayerData, class AFortPlayerStateAthena* InPlayerState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerStateChanged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnPlayerStateChanged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InPlayerState = InPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnShieldDamaged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InShield                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InShieldMax                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnShieldDamaged(class UAthenaRemotePlayerViewData* InPlayerData, float InShield, float InShieldMax)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnShieldDamaged");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnShieldDamaged Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InShield = InShield;
	Parms.InShieldMax = InShieldMax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.OnShieldHealed
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UAthenaRemotePlayerViewData*      InPlayerData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InShield                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InShieldMax                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::OnShieldHealed(class UAthenaRemotePlayerViewData* InPlayerData, float InShield, float InShieldMax)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnShieldHealed");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_OnShieldHealed Parms{};

	Parms.InPlayerData = InPlayerData;
	Parms.InShield = InShield;
	Parms.InShieldMax = InShieldMax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.SetEliminationsVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bVisible                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaEventMatchPlayerGridPlayerWidget_C::SetEliminationsVisibility(bool bVisible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetEliminationsVisibility");

	Params::AthenaEventMatchPlayerGridPlayerWidget_C_SetEliminationsVisibility Parms{};

	Parms.bVisible = bVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.SetupBackgrounds
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::SetupBackgrounds()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetupBackgrounds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.StopDamageAnimations
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::StopDamageAnimations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StopDamageAnimations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.UpdateBackground
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::UpdateBackground()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateBackground");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.UpdateHitPointBars
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::UpdateHitPointBars()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateHitPointBars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.UpdateKillsWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::UpdateKillsWidget()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateKillsWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.UpdateNameText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::UpdateNameText()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateNameText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaEventMatchPlayerGridPlayerWidget.AthenaEventMatchPlayerGridPlayerWidget_C.UpdateStatus
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaEventMatchPlayerGridPlayerWidget_C::UpdateStatus()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateStatus");

	UObject::ProcessEvent(Func, nullptr);
}

}

