#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Artemis_FlopperSpawnWorld_Placement

#include "Basic.hpp"

#include "B_Artemis_FlopperSpawnWorld_Placement_classes.hpp"
#include "B_Artemis_FlopperSpawnWorld_Placement_parameters.hpp"


namespace SDK
{

// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.StartWaterBodySpawn
// (BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::StartWaterBodySpawn()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StartWaterBodySpawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.StartEQSSpawn
// (BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::StartEQSSpawn()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StartEQSSpawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.Spawn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform                       SpawnTransform                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// int32                                   ItemIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Artemis_FlopperSpawnWorld_Placement_C::Spawn(const struct FTransform& SpawnTransform, int32 ItemIndex)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Spawn");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_Spawn Parms{};

	Parms.SpawnTransform = std::move(SpawnTransform);
	Parms.ItemIndex = ItemIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.RollRarity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EFortRarity                             RarityOut                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Artemis_FlopperSpawnWorld_Placement_C::RollRarity(EFortRarity* RarityOut)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RollRarity");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_RollRarity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RarityOut != nullptr)
		*RarityOut = Parms.RarityOut;
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.OnReady_FDC1A68B4F1D24CA5D5C0EB7F4616663
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AB_Artemis_FlopperSpawnWorld_Placement_C::OnReady_FDC1A68B4F1D24CA5D5C0EB7F4616663(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnReady_FDC1A68B4F1D24CA5D5C0EB7F4616663");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_OnReady_FDC1A68B4F1D24CA5D5C0EB7F4616663 Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.GetNormal
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USplineComponent*                 Spline                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Distance                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector AB_Artemis_FlopperSpawnWorld_Placement_C::GetNormal(class USplineComponent* Spline, float Distance)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetNormal");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_GetNormal Parms{};

	Parms.Spline = Spline;
	Parms.Distance = Distance;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindRiverWideLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindRiverWideLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindRiverWideLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindRiverNarrowLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindRiverNarrowLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindRiverNarrowLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindOceanLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindOceanLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindOceanLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindLakeLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindLakeLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindLakeLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindIslandLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindIslandLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindIslandLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.FindCustomSplineLocations
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Artemis_FlopperSpawnWorld_Placement_C::FindCustomSplineLocations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FindCustomSplineLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.ExecuteUbergraph_B_Artemis_FlopperSpawnWorld_Placement
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Artemis_FlopperSpawnWorld_Placement_C::ExecuteUbergraph_B_Artemis_FlopperSpawnWorld_Placement(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_B_Artemis_FlopperSpawnWorld_Placement");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_ExecuteUbergraph_B_Artemis_FlopperSpawnWorld_Placement Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C.EQS Finished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UEnvQueryInstanceBlueprintWrapper*QueryInstance_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnvQueryStatus                         QueryStatus                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Artemis_FlopperSpawnWorld_Placement_C::EQS_Finished(class UEnvQueryInstanceBlueprintWrapper* QueryInstance_0, EEnvQueryStatus QueryStatus)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EQS Finished");

	Params::B_Artemis_FlopperSpawnWorld_Placement_C_EQS_Finished Parms{};

	Parms.QueryInstance_0 = QueryInstance_0;
	Parms.QueryStatus = QueryStatus;

	UObject::ProcessEvent(Func, &Parms);
}

}

