#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_HappyGhost_Wire

#include "Basic.hpp"

#include "B_Athena_HappyGhost_Wire_classes.hpp"
#include "B_Athena_HappyGhost_Wire_parameters.hpp"


namespace SDK
{

// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.AttachNonFishingPickups
// (Net, NetReliable, NetMulticast, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPickup*                      InputPin                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_HappyGhost_Wire_C::AttachNonFishingPickups(const class AFortPickup*& InputPin)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AttachNonFishingPickups");

	Params::B_Athena_HappyGhost_Wire_C_AttachNonFishingPickups Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.BounceOff__FinishedFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::BounceOff__FinishedFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BounceOff__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.BounceOff__UpdateFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::BounceOff__UpdateFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BounceOff__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.DropAndDestroy
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::DropAndDestroy()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("DropAndDestroy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.End Reel
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::End_Reel()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("End Reel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.ExecuteUbergraph_B_Athena_HappyGhost_Wire
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_HappyGhost_Wire_C::ExecuteUbergraph_B_Athena_HappyGhost_Wire(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_B_Athena_HappyGhost_Wire");

	Params::B_Athena_HappyGhost_Wire_C_ExecuteUbergraph_B_Athena_HappyGhost_Wire Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.PlayMontage
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::PlayMontage()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlayMontage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.Reel In__FinishedFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::Reel_In__FinishedFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Reel In__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.Reel In__UpdateFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::Reel_In__UpdateFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Reel In__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.ReelFinished
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::ReelFinished()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReelFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.ReelFinishedClientOnly
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::ReelFinishedClientOnly()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReelFinishedClientOnly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.Tight__FinishedFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::Tight__FinishedFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Tight__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.Tight__UpdateFunc
// (BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::Tight__UpdateFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Tight__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_HappyGhost_Wire.B_Athena_HappyGhost_Wire_C.TightenRope
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_HappyGhost_Wire_C::TightenRope()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TightenRope");

	UObject::ProcessEvent(Func, nullptr);
}

}

