#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_PlayerSpawnedBall

#include "Basic.hpp"

#include "B_PlayerSpawnedBall_classes.hpp"
#include "B_PlayerSpawnedBall_parameters.hpp"


namespace SDK
{

// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.ExecuteUbergraph_B_PlayerSpawnedBall
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_PlayerSpawnedBall_C::ExecuteUbergraph_B_PlayerSpawnedBall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_B_PlayerSpawnedBall");

	Params::B_PlayerSpawnedBall_C_ExecuteUbergraph_B_PlayerSpawnedBall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.InitializeToyInstance
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerController*            OwningPC                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NumTimesSummoned                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_PlayerSpawnedBall_C::InitializeToyInstance(class AFortPlayerController* OwningPC, int32 NumTimesSummoned)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeToyInstance");

	Params::B_PlayerSpawnedBall_C_InitializeToyInstance Parms{};

	Parms.OwningPC = OwningPC;
	Parms.NumTimesSummoned = NumTimesSummoned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.InitializeToyPreviewInFrontend
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_PlayerSpawnedBall_C::InitializeToyPreviewInFrontend()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeToyPreviewInFrontend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.NotifyToyInstanceOfReuse
// (Event, Public, BlueprintEvent)

void AB_PlayerSpawnedBall_C::NotifyToyInstanceOfReuse()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("NotifyToyInstanceOfReuse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.PlayCueCenteredOnMe
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     GameplayCueToPlay                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// float                                   Raw_Magnitude                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_PlayerSpawnedBall_C::PlayCueCenteredOnMe(const struct FGameplayTag& GameplayCueToPlay, float Raw_Magnitude)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlayCueCenteredOnMe");

	Params::B_PlayerSpawnedBall_C_PlayCueCenteredOnMe Parms{};

	Parms.GameplayCueToPlay = std::move(GameplayCueToPlay);
	Parms.Raw_Magnitude = Raw_Magnitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_PlayerSpawnedBall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_PlayerSpawnedBall.B_PlayerSpawnedBall_C.StartToyFadeOutDueToNewPlacement
// (Event, Public, BlueprintEvent)

void AB_PlayerSpawnedBall_C::StartToyFadeOutDueToNewPlacement()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StartToyFadeOutDueToNewPlacement");

	UObject::ProcessEvent(Func, nullptr);
}

}

