#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AISpawnerComp_Cover_Phoebe

#include "Basic.hpp"

#include "FortniteAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AISpawnerComp_Cover_Phoebe.BP_AISpawnerComp_Cover_Phoebe_C
// 0x0000 (0x0058 - 0x0058)
class UBP_AISpawnerComp_Cover_Phoebe_C final : public UFortAthenaAISpawnerDataComponent_CoverBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AISpawnerComp_Cover_Phoebe_C">();
	}
	static class UBP_AISpawnerComp_Cover_Phoebe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AISpawnerComp_Cover_Phoebe_C>();
	}
};
static_assert(alignof(UBP_AISpawnerComp_Cover_Phoebe_C) == 0x000008, "Wrong alignment on UBP_AISpawnerComp_Cover_Phoebe_C");
static_assert(sizeof(UBP_AISpawnerComp_Cover_Phoebe_C) == 0x000058, "Wrong size on UBP_AISpawnerComp_Cover_Phoebe_C");

}

