#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PerkData_Phoebe_Evasive_Melee_DoNothing

#include "Basic.hpp"

#include "FortniteAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PerkData_Phoebe_Evasive_Melee_DoNothing.BP_PerkData_Phoebe_Evasive_Melee_DoNothing_C
// 0x0000 (0x0458 - 0x0458)
class UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C final : public UFortAthenaAIPerk_EvasiveManeuvers
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PerkData_Phoebe_Evasive_Melee_DoNothing_C">();
	}
	static class UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C>();
	}
};
static_assert(alignof(UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C) == 0x000008, "Wrong alignment on UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C");
static_assert(sizeof(UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C) == 0x000458, "Wrong size on UBP_PerkData_Phoebe_Evasive_Melee_DoNothing_C");

}

