#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PerkData_Phoebe_Bunker

#include "Basic.hpp"

#include "FortniteAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PerkData_Phoebe_Bunker.BP_PerkData_Phoebe_Bunker_C
// 0x0000 (0x02A8 - 0x02A8)
class UBP_PerkData_Phoebe_Bunker_C final : public UFortAthenaAIPerk_Bunker
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PerkData_Phoebe_Bunker_C">();
	}
	static class UBP_PerkData_Phoebe_Bunker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PerkData_Phoebe_Bunker_C>();
	}
};
static_assert(alignof(UBP_PerkData_Phoebe_Bunker_C) == 0x000008, "Wrong alignment on UBP_PerkData_Phoebe_Bunker_C");
static_assert(sizeof(UBP_PerkData_Phoebe_Bunker_C) == 0x0002A8, "Wrong size on UBP_PerkData_Phoebe_Bunker_C");

}

