#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DaDoorHealthWidget

#include "Basic.hpp"

#include "DaDoorHealthWidget_classes.hpp"
#include "DaDoorHealthWidget_parameters.hpp"


namespace SDK
{

// Function DaDoorHealthWidget.DaDoorHealthWidget_C.ChangeWidgetVisibleDuration
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   StatusWidgetVisibleDuration_0                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDaDoorHealthWidget_C::ChangeWidgetVisibleDuration(float StatusWidgetVisibleDuration_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ChangeWidgetVisibleDuration");

	Params::DaDoorHealthWidget_C_ChangeWidgetVisibleDuration Parms{};

	Parms.StatusWidgetVisibleDuration_0 = StatusWidgetVisibleDuration_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDaDoorHealthWidget_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.EventHideStatus
// (BlueprintCallable, BlueprintEvent)

void UDaDoorHealthWidget_C::EventHideStatus()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventHideStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.EventShowNumbers
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int64                                   Health                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDaDoorHealthWidget_C::EventShowNumbers(int64 Health)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventShowNumbers");

	Params::DaDoorHealthWidget_C_EventShowNumbers Parms{};

	Parms.Health = Health;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.EventUpdateStatus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Health                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Shield                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ShowShield                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDaDoorHealthWidget_C::EventUpdateStatus(float Health, float Shield, bool ShowShield)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventUpdateStatus");

	Params::DaDoorHealthWidget_C_EventUpdateStatus Parms{};

	Parms.Health = Health;
	Parms.Shield = Shield;
	Parms.ShowShield = ShowShield;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.ExecuteUbergraph_DaDoorHealthWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDaDoorHealthWidget_C::ExecuteUbergraph_DaDoorHealthWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_DaDoorHealthWidget");

	Params::DaDoorHealthWidget_C_ExecuteUbergraph_DaDoorHealthWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.SetKeepVisibilityOn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    KeepVisibilityOn_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDaDoorHealthWidget_C::SetKeepVisibilityOn(bool KeepVisibilityOn_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetKeepVisibilityOn");

	Params::DaDoorHealthWidget_C_SetKeepVisibilityOn Parms{};

	Parms.KeepVisibilityOn_0 = KeepVisibilityOn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DaDoorHealthWidget.DaDoorHealthWidget_C.TryCallEventHideByTimer
// (BlueprintCallable, BlueprintEvent)

void UDaDoorHealthWidget_C::TryCallEventHideByTimer()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TryCallEventHideByTimer");

	UObject::ProcessEvent(Func, nullptr);
}

}

