#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortPostGameNewQuestsWidget

#include "Basic.hpp"

#include "FortPostGameNewQuestsWidget_classes.hpp"
#include "FortPostGameNewQuestsWidget_parameters.hpp"


namespace SDK
{

// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.ExecuteUbergraph_FortPostGameNewQuestsWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFortPostGameNewQuestsWidget_C::ExecuteUbergraph_FortPostGameNewQuestsWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_FortPostGameNewQuestsWidget");

	Params::FortPostGameNewQuestsWidget_C_ExecuteUbergraph_FortPostGameNewQuestsWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.HandleEntryBoxIntroFinished
// (BlueprintCallable, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::HandleEntryBoxIntroFinished()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleEntryBoxIntroFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.HandleEntryBoxOutroFinished
// (BlueprintCallable, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::HandleEntryBoxOutroFinished()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleEntryBoxOutroFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.HandleIntroFinished
// (BlueprintCallable, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::HandleIntroFinished()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleIntroFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::OnInitialized()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.OnPlayIntro
// (Event, Protected, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::OnPlayIntro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayIntro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.OnPlayNewQuestsEntryBoxIntro
// (Event, Protected, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::OnPlayNewQuestsEntryBoxIntro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayNewQuestsEntryBoxIntro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.OnPlayNewQuestsEntryBoxOutro
// (Event, Protected, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::OnPlayNewQuestsEntryBoxOutro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayNewQuestsEntryBoxOutro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FortPostGameNewQuestsWidget.FortPostGameNewQuestsWidget_C.OnPlayOutro
// (Event, Protected, BlueprintEvent)

void UFortPostGameNewQuestsWidget_C::OnPlayOutro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayOutro");

	UObject::ProcessEvent(Func, nullptr);
}

}

