#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IconTextButtonReplay

#include "Basic.hpp"

#include "IconTextButtonReplay_classes.hpp"
#include "IconTextButtonReplay_parameters.hpp"


namespace SDK
{

// Function IconTextButtonReplay.IconTextButtonReplay_C.ActivateButton
// (Public, BlueprintCallable, BlueprintEvent)

void UIconTextButtonReplay_C::ActivateButton()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ActivateButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.BndEvt__CommonActionWidgetAction_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bUsingGamepad                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::BndEvt__CommonActionWidgetAction_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature(bool bUsingGamepad)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__CommonActionWidgetAction_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature");

	Params::IconTextButtonReplay_C_BndEvt__CommonActionWidgetAction_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature Parms{};

	Parms.bUsingGamepad = bUsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UIconTextButtonReplay_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.ExecuteUbergraph_IconTextButtonReplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::ExecuteUbergraph_IconTextButtonReplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_IconTextButtonReplay");

	Params::IconTextButtonReplay_C_ExecuteUbergraph_IconTextButtonReplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.InitializeButton
// (Public, BlueprintCallable, BlueprintEvent)

void UIconTextButtonReplay_C::InitializeButton()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.OnActionComplete
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::OnActionComplete()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnActionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.OnActionProgress
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   HeldPercent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::OnActionProgress(float HeldPercent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnActionProgress");

	Params::IconTextButtonReplay_C_OnActionProgress Parms{};

	Parms.HeldPercent = HeldPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.OnCurrentTextStyleChanged
// (Event, Protected, BlueprintEvent)

void UIconTextButtonReplay_C::OnCurrentTextStyleChanged()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCurrentTextStyleChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.OnTriggeredInputActionChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FDataTableRowHandle              NewTriggeredAction                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UIconTextButtonReplay_C::OnTriggeredInputActionChanged(const struct FDataTableRowHandle& NewTriggeredAction)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnTriggeredInputActionChanged");

	Params::IconTextButtonReplay_C_OnTriggeredInputActionChanged Parms{};

	Parms.NewTriggeredAction = std::move(NewTriggeredAction);

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::IconTextButtonReplay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.Set Icon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateBrush                      IconBrush_0                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UIconTextButtonReplay_C::Set_Icon(const struct FSlateBrush& IconBrush_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Set Icon");

	Params::IconTextButtonReplay_C_Set_Icon Parms{};

	Parms.IconBrush_0 = std::move(IconBrush_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.SetContentAlignment
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EHorizontalAlignment                    ContentAlignment_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::SetContentAlignment(EHorizontalAlignment ContentAlignment_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetContentAlignment");

	Params::IconTextButtonReplay_C_SetContentAlignment Parms{};

	Parms.ContentAlignment_0 = ContentAlignment_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.SetControllerStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ControllerInputStyle_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::SetControllerStyle(class UClass* ControllerInputStyle_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetControllerStyle");

	Params::IconTextButtonReplay_C_SetControllerStyle Parms{};

	Parms.ControllerInputStyle_0 = ControllerInputStyle_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.SetMouseKeyboardStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ControllerInputStyle_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::SetMouseKeyboardStyle(class UClass* ControllerInputStyle_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMouseKeyboardStyle");

	Params::IconTextButtonReplay_C_SetMouseKeyboardStyle Parms{};

	Parms.ControllerInputStyle_0 = ControllerInputStyle_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.SetTabLabelInfo
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFortTabButtonLabelInfo          TabLabelInfo                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UIconTextButtonReplay_C::SetTabLabelInfo(const struct FFortTabButtonLabelInfo& TabLabelInfo)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetTabLabelInfo");

	Params::IconTextButtonReplay_C_SetTabLabelInfo Parms{};

	Parms.TabLabelInfo = std::move(TabLabelInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.SetText
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UIconTextButtonReplay_C::SetText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetText");

	Params::IconTextButtonReplay_C_SetText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.UpdateContentAlignment
// (Private, BlueprintCallable, BlueprintEvent)

void UIconTextButtonReplay_C::UpdateContentAlignment()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateContentAlignment");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.UpdateStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    UsingGamepad                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::UpdateStyle(bool UsingGamepad)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateStyle");

	Params::IconTextButtonReplay_C_UpdateStyle Parms{};

	Parms.UsingGamepad = UsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.UpdateText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UIconTextButtonReplay_C::UpdateText()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.UpdateTextAndStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bUsingGamepad                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UIconTextButtonReplay_C::UpdateTextAndStyle(bool bUsingGamepad)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateTextAndStyle");

	Params::IconTextButtonReplay_C_UpdateTextAndStyle Parms{};

	Parms.bUsingGamepad = bUsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function IconTextButtonReplay.IconTextButtonReplay_C.UpdateTextStyle
// (Public, BlueprintCallable, BlueprintEvent)

void UIconTextButtonReplay_C::UpdateTextStyle()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateTextStyle");

	UObject::ProcessEvent(Func, nullptr);
}

}

