#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KeepPlayingTogetherOverlay

#include "Basic.hpp"

#include "KeepPlayingTogetherOverlay_classes.hpp"
#include "KeepPlayingTogetherOverlay_parameters.hpp"


namespace SDK
{

// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.ExecuteUbergraph_KeepPlayingTogetherOverlay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKeepPlayingTogetherOverlay_C::ExecuteUbergraph_KeepPlayingTogetherOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_KeepPlayingTogetherOverlay");

	Params::KeepPlayingTogetherOverlay_C_ExecuteUbergraph_KeepPlayingTogetherOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnExitToLobbyCountdownProgressed
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   CountdownValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKeepPlayingTogetherOverlay_C::OnExitToLobbyCountdownProgressed(float CountdownValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExitToLobbyCountdownProgressed");

	Params::KeepPlayingTogetherOverlay_C_OnExitToLobbyCountdownProgressed Parms{};

	Parms.CountdownValue = CountdownValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnKeepPlayingTogetherScreenOverlayActivated
// (Event, Protected, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::OnKeepPlayingTogetherScreenOverlayActivated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnKeepPlayingTogetherScreenOverlayActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnKeepPlayingTogetherScreenOverlayDeactivated
// (Event, Protected, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::OnKeepPlayingTogetherScreenOverlayDeactivated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnKeepPlayingTogetherScreenOverlayDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnMatchmakingFinished
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bSuccess                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKeepPlayingTogetherOverlay_C::OnMatchmakingFinished(bool bSuccess)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchmakingFinished");

	Params::KeepPlayingTogetherOverlay_C_OnMatchmakingFinished Parms{};

	Parms.bSuccess = bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnMatchmakingStarted
// (Event, Protected, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::OnMatchmakingStarted()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchmakingStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnPreMatchmakingCountdownProgressed
// (Event, Protected, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::OnPreMatchmakingCountdownProgressed()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPreMatchmakingCountdownProgressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.OnPreMatchmakingCountdownStarted
// (Event, Protected, BlueprintEvent)

void UKeepPlayingTogetherOverlay_C::OnPreMatchmakingCountdownStarted()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPreMatchmakingCountdownStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKeepPlayingTogetherOverlay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::KeepPlayingTogetherOverlay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KeepPlayingTogetherOverlay.KeepPlayingTogetherOverlay_C.UpdateExitToLobbyCountdownText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CountdownValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKeepPlayingTogetherOverlay_C::UpdateExitToLobbyCountdownText(float CountdownValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateExitToLobbyCountdownText");

	Params::KeepPlayingTogetherOverlay_C_UpdateExitToLobbyCountdownText Parms{};

	Parms.CountdownValue = CountdownValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

