#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestNotification

#include "Basic.hpp"

#include "QuestNotification_classes.hpp"
#include "QuestNotification_parameters.hpp"


namespace SDK
{

// Function QuestNotification.QuestNotification_C.BP_OnRaritySet
// (Event, Protected, BlueprintEvent)
// Parameters:
// EFortRarity                             Rarity                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::BP_OnRaritySet(EFortRarity Rarity)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnRaritySet");

	Params::QuestNotification_C_BP_OnRaritySet Parms{};

	Parms.Rarity = Rarity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.BP_OnTimerSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// EAthenaChallengeTimerState              TimerState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::BP_OnTimerSet(EAthenaChallengeTimerState TimerState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnTimerSet");

	Params::QuestNotification_C_BP_OnTimerSet Parms{};

	Parms.TimerState = TimerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.EventCompleteAnim
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::EventCompleteAnim()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventCompleteAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.EventFillComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::EventFillComplete()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventFillComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.EventOnIntroStart
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::EventOnIntroStart()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventOnIntroStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.EventOnStartComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::EventOnStartComplete()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventOnStartComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.EventReset
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::EventReset()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.ExecuteUbergraph_QuestNotification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::ExecuteUbergraph_QuestNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_QuestNotification");

	Params::QuestNotification_C_ExecuteUbergraph_QuestNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.OnEnableCompleteFlavorText
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsEnabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::OnEnableCompleteFlavorText(bool IsEnabled)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEnableCompleteFlavorText");

	Params::QuestNotification_C_OnEnableCompleteFlavorText Parms{};

	Parms.IsEnabled = IsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UQuestNotification_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnFocusLost");

	Params::QuestNotification_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UQuestNotification_C::OnInitialized()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.OnPlayRushedNotificationIntro
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::OnPlayRushedNotificationIntro(float Rate)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayRushedNotificationIntro");

	Params::QuestNotification_C_OnPlayRushedNotificationIntro Parms{};

	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.OnUpdateNotificationBackground
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bUseRarityContainer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsDailyPunchcardQuest                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::OnUpdateNotificationBackground(bool bUseRarityContainer, bool bIsDailyPunchcardQuest)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnUpdateNotificationBackground");

	Params::QuestNotification_C_OnUpdateNotificationBackground Parms{};

	Parms.bUseRarityContainer = bUseRarityContainer;
	Parms.bIsDailyPunchcardQuest = bIsDailyPunchcardQuest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestNotification_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::QuestNotification_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.SetAssistData
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bWasAssisted                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           OtherPlayersName                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UQuestNotification_C::SetAssistData(bool bWasAssisted, const class FString& OtherPlayersName)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetAssistData");

	Params::QuestNotification_C_SetAssistData Parms{};

	Parms.bWasAssisted = bWasAssisted;
	Parms.OtherPlayersName = std::move(OtherPlayersName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestNotification.QuestNotification_C.StartNotificationIntro
// (Event, Protected, BlueprintEvent)

void UQuestNotification_C::StartNotificationIntro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StartNotificationIntro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.StartNotificationOutro
// (Event, Public, BlueprintEvent)

void UQuestNotification_C::StartNotificationOutro()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StartNotificationOutro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.TurnInNotification
// (BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::TurnInNotification()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TurnInNotification");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.UpdateDefaultObjectiveVisuals
// (Event, Public, BlueprintEvent)

void UQuestNotification_C::UpdateDefaultObjectiveVisuals()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateDefaultObjectiveVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.UpdateProgress
// (Public, BlueprintCallable, BlueprintEvent)

void UQuestNotification_C::UpdateProgress()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateProgress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestNotification.QuestNotification_C.UpdateQuestVisuals
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FFortChallengeSetStyle           DisplayStyle                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UQuestNotification_C::UpdateQuestVisuals(const struct FFortChallengeSetStyle& DisplayStyle)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateQuestVisuals");

	Params::QuestNotification_C_UpdateQuestVisuals Parms{};

	Parms.DisplayStyle = std::move(DisplayStyle);

	UObject::ProcessEvent(Func, &Parms);
}

}

