#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReadyUpScreenOverlay

#include "Basic.hpp"

#include "ReadyUpScreenOverlay_classes.hpp"
#include "ReadyUpScreenOverlay_parameters.hpp"


namespace SDK
{

// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UReadyUpScreenOverlay_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.ExecuteUbergraph_ReadyUpScreenOverlay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReadyUpScreenOverlay_C::ExecuteUbergraph_ReadyUpScreenOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_ReadyUpScreenOverlay");

	Params::ReadyUpScreenOverlay_C_ExecuteUbergraph_ReadyUpScreenOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnCancelReadyUp
// (Event, Protected, BlueprintEvent)

void UReadyUpScreenOverlay_C::OnCancelReadyUp()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCancelReadyUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnCountdownProgressed
// (Event, Protected, BlueprintEvent)

void UReadyUpScreenOverlay_C::OnCountdownProgressed()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCountdownProgressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnCountdownStarted
// (Event, Protected, BlueprintEvent)

void UReadyUpScreenOverlay_C::OnCountdownStarted()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnCountdownStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnExitToLobbyCountdownProgressed
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   CountdownValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReadyUpScreenOverlay_C::OnExitToLobbyCountdownProgressed(float CountdownValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExitToLobbyCountdownProgressed");

	Params::ReadyUpScreenOverlay_C_OnExitToLobbyCountdownProgressed Parms{};

	Parms.CountdownValue = CountdownValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnMatchmakingFinished
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bSuccess                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReadyUpScreenOverlay_C::OnMatchmakingFinished(bool bSuccess)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchmakingFinished");

	Params::ReadyUpScreenOverlay_C_OnMatchmakingFinished Parms{};

	Parms.bSuccess = bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnMatchmakingStarted
// (Event, Protected, BlueprintEvent)

void UReadyUpScreenOverlay_C::OnMatchmakingStarted()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchmakingStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.OnReadyUp
// (Event, Protected, BlueprintEvent)

void UReadyUpScreenOverlay_C::OnReadyUp()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnReadyUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReadyUpScreenOverlay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::ReadyUpScreenOverlay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ReadyUpScreenOverlay.ReadyUpScreenOverlay_C.UpdateExitToLobbyCountdownText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CountdownValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UReadyUpScreenOverlay_C::UpdateExitToLobbyCountdownText(float CountdownValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateExitToLobbyCountdownText");

	Params::ReadyUpScreenOverlay_C_UpdateExitToLobbyCountdownText Parms{};

	Parms.CountdownValue = CountdownValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

