#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Valet_SportsCar_VehicleConfigs_Upgrade

#include "Basic.hpp"

#include "Valet_SportsCar_VehicleConfig_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Valet_SportsCar_VehicleConfigs_Upgrade.Valet_SportsCar_VehicleConfigs_Upgrade_C
// 0x0000 (0x0960 - 0x0960)
class UValet_SportsCar_VehicleConfigs_Upgrade_C final : public UValet_SportsCar_VehicleConfig_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Valet_SportsCar_VehicleConfigs_Upgrade_C">();
	}
	static class UValet_SportsCar_VehicleConfigs_Upgrade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UValet_SportsCar_VehicleConfigs_Upgrade_C>();
	}
};
static_assert(alignof(UValet_SportsCar_VehicleConfigs_Upgrade_C) == 0x000008, "Wrong alignment on UValet_SportsCar_VehicleConfigs_Upgrade_C");
static_assert(sizeof(UValet_SportsCar_VehicleConfigs_Upgrade_C) == 0x000960, "Wrong size on UValet_SportsCar_VehicleConfigs_Upgrade_C");

}

